### ISSUE TITLE
Receiver

### ISSUE THREAD

**Issue by capedra** [maxmacstn/MQTT-AC-Controller#3]
Where’s the photodiode or TSOP? How can you dump data when there’s no photoreceiver in your schematic? Thanks!

**Comment by maxmacstn** [comment]
I create test circuit with receiver and sender in my prototype version and record all of the required IR timing data. After that, I can use that IR timing data and send it. So, the photodiode is not required in final design.

my simple prototype.
https://maxmacstn.files.wordpress.com/2019/01/photo6174604148083894335.jpg?w=736
